### PR TITLE
Add_Open_Directory

### PR DESCRIPTION
**Pull request by mikeleg**
Add open directory

### CODE REVIEW

**Comment by suda** [comment]
@mikeleg could you fix the whitespace first? It messes up the diff :)

**Comment by mikeleg** [comment]
I which way a can fix it?

**Comment by jerone** [comment]
[**@mikeleg**](https://github.com/mikeleg) commented on [8 sep. 2015 16:06 CEST](https://github.com/suda/toolbar-main/pull/8#issuecomment-138570077 "2015-09-08T14:06:56Z - Replied by Github Comment Enhancer"):
> I which way a can fix it?


[**@mikeleg**](https://github.com/mikeleg) commented on [8 sep. 2015 16:06 CEST](https://github.com/suda/toolbar-main/pull/8#issuecomment-138570077 "2015-09-08T14:06:56Z - Replied by Github Comment Enhancer"):
> I which way a can fix it?

This project uses two space for every tab.

**Comment by jerone** [comment]
Thanks for this PR. However, I recommend using [Flex Tool Bar](https://atom.io/packages/flex-tool-bar) for defining your own buttons.

**Pull request closed without merging**
